# Generated by Django 3.1.3 on 2020-11-23 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201111_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ip',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='public_key',
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='is_live',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='private_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
