# Generated by Django 3.1.3 on 2021-01-25 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_auto_20210104_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FR', 'Friend')], default='FR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connectees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
