# Generated by Django 3.1.3 on 2021-01-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_socialconnection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialconnection',
            old_name='type',
            new_name='conn_type',
        ),
    ]
