# Generated by Django 3.1.3 on 2021-01-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210125_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
